feat(menu): add options for hiding menu items
cnblogs/vscode-cnb pull request #110
Opened 2023-03-05 07:38 UTC by Higurashi-kagome

尝试支持控制右键菜单显示项，不常用的菜单项可隐藏。

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/222947871-61ade8e5-0b3f-45cd-ade3-06a050849582.png)

</details>

2023-03-16 08:20 UTC, laggage requested changes
这个自定义配置挺有用的，感谢贡献👍，考虑修改后在v1.7中一起发布

如果你最近没时间修改的话，可以告知一下，我这边可以直接帮忙修改

2023-03-16 08:20 UTC, laggage commented on package.json
> +                            ]
这里建议增加 `enumItemLabels` 保存中文描述（参考 `cnblogsClientForVSCode.automaticallyExtractImages` 配置项），`enum` 字段应该全部是 `CommandId`

2023-03-16 08:20 UTC, laggage commented on package.json
> +                            ]
同上应该通过 `enumItemLabels` 保存中文描述

2023-03-16 10:15 UTC, Higurashi-kagome commented
确实有一点事，麻烦帮助完善。 @laggage

2023-03-20 06:37 UTC, laggage commented
由于缺少force push权限，将另起一个新pr，commit中会标记co-author

2023-03-20 06:37 UTC, closed without merging